### ISSUE TITLE
Authorizer V2 not configured. Skipping privilege checking

### ISSUE THREAD

**Issue by Step1N** [yaooqinn/spark-authorizer#17]
Hi,

I was trying to integrate this spark sql extension with spark 2.3.1. I have build jar after cloning the repo as mentioned in readme and added build authorizer jar to $SPARK_HOME/jars. 
I have ranger install on a machine. I have installed hive plugin on hive to enable ranger policy for hive users.
But whenever am trying to use this authorizer it always says warning 

scala> spark.sql("show databases").show
19/02/28 08:26:49 WARN AuthzImpl$: Authorizer V2 not configured. Skipping privilege checking

I am not sure what i missed

**Comment by yaooqinn** [comment]
please follow this doc https://yaooqinn.github.io/spark-authorizer/docs/install_plugin.html

**Comment by Step1N** [comment]
thanks for quick response, I gone through document but still facing same issue. One thing i wanted to point out am using hive metastore, will that cause any issue

**Comment by yaooqinn** [comment]
the warning message told you that you didn't configure hive authorizer properly in hive-site.xml, which you may find in that doc.

**Comment by Step1N** [comment]
thanks @yaooqinn 
I am able to configure now. It was issue with hive-site.xml. But It is not able parse ranger policies. Its throwing following error -

ERROR PolicyRefresher: PolicyRefresher(serviceName=hiveService): failed to refresh policies. Will continue to use last known version of policies (-1)
com.sun.jersey.api.client.ClientHandlerException: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: 
Unrecognized field "accessTypeRestrictions" (Class org.apache.ranger.plugin.model.RangerServiceDef$RangerResourceDef), not marked as ignorable
--------------------------------------------------------------------------------------------------
Spark 2.3.1
Hive 2.3.3
Ranger - 0.5.3

Am going to downgrade my spark version then i will see whether this issue get fix or not

**Comment by Step1N** [comment]
thanks @yaooqinn 
I have integrated it and its working pretty good. Going ahead am looking to make few changes. 
I will keep you posted.

Thanks again

**Comment by ssaniva** [comment]
Hi @Step1N @yaooqinn 
I was facing the same issue,  (Authorizer V2 not configured. Skipping privilege checking)
and I did everything that mentioned above, Still unable to resolve this 
May I know if downgrading your spark version resolved this issue, what's the Version you've degraded  the spark to  ?
I was using Spark 2.3.1, Hive 2.3.3, Ranger -1.0                    
 Any help in regards to this issue is very much appreciated.

**Comment by ssaniva** [comment]
Hi @Step1N @yaooqinn 
Does the link below works only with Ranger version 0.5.3 or we can use any higher versions such as 0.6 ?
https://yaooqinn.github.io/spark-authorizer/
Thanks in advance

**Comment by Step1N** [comment]
Hi @ssaniva ,

I tried it with ranger version 0.6 but it did not work, So i downgraded ranger version 0.5.3. And its working fine.

**Comment by ssaniva** [comment]
Thanks @Step1N for your response, Do you know where exactly I can find that ranger 0.5.3 Jar, I did tried but facing dependency issues while building it.

**Comment by ssaniva** [comment]
thanks @Step1N for responding back, If possible can you send me the URL for having that ranger 0.5.3, I did tried to build it but facing dependency issues .

**Comment by ssaniva** [comment]
thanks @Step1N, what's the spark version that is supporting it ?

**Comment by Step1N** [comment]
Hi,

Spark 2.3.1
Hive 2.3.3
Ranger - 0.5.3

**Comment by ssaniva** [comment]
thanks @Step1N, Is your data sitting locally on HDFS or pulling it from S3.
Also, does the spark-authorizer extension support column masking and row-level filtering access policies from ranger? I wasn't able to enforce masking rule on a column so wondering if this extension supports such finer grain access control in your experience?
@yaooqinn any ideas...^?

**Comment by yaooqinn** [comment]
@ssaniva wip with apache ranger community

**Comment by ssaniva** [comment]
thanks @yaooqinn for the information .
