### ISSUE TITLE
该项目不支持PySpark权限校验，请问为啥走不到这个Extension逻辑呀

### ISSUE THREAD

**Issue by southernriver** [yaooqinn/spark-authorizer#33]
**Describe the bug**

**To Reproduce**
1. Configurations
2. Environments
3. Operations

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by southernriver** [comment]
感谢，找到了你发的issue：https://issues.apache.org/jira/browse/SPARK-25003

**Comment by yaooqinn** [comment]
是的。
